version: '3.9'
name: 'demo-winker-csouza'

services:
  #Data Base
  postgres:
    hostname: postgres
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=demo-winker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #    volumes:
    #      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    #    command: 'postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
    ports:
      - "5432:5432"
    networks:
      - demo-winker-network

  nginx:
    hostname: nginx
    image: nginx:alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '200MB'
    ports:
      - "8080:8080"
    networks:
      - demo-winker-network

  api1:
    image: Demo-Winker
    hostname: api1
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
    networks:
      - app-network


networks:
  demo-winker-network: